added note section
teziapp/clipboard-extension pull request #2
Opened 2024-11-15 19:42 UTC by Hamzaisongit

mainly worked on UI, and synced it with dexie.. didn't hamper any of the previous features,
 yet to work on content script, it doesn't do anything yet

2024-11-15 19:46 UTC, Hamzaisongit commented on src/pages/Background/index.js
> +// db.symbols.bulkAdd([
dummy data, just for testing the ui

2024-11-16 16:55 UTC, krishna-404 requested changes
Too big update. Please break down into micro-PRs as discussed.

2024-11-16 16:55 UTC, krishna-404 commented on src/Dexie/DexieStore.js
> +            break;
you can replace this with `return db.notes.Array()`

2024-11-16 16:55 UTC, krishna-404 commented on src/Dexie/DexieStore.js
> +            break;
can replace this with `return db.notes.where('symId').equals(activeSymbol.symId).toArray()`

2024-11-16 16:55 UTC, krishna-404 commented on src/Dexie/DexieStore.js
> +            break;
didnt understand whats happening here.

2024-11-16 16:55 UTC, krishna-404 commented on README.md
> +- All previous features
A Readme file should always be timeless. There is no previous/before in a readme file.

2024-11-16 16:55 UTC, krishna-404 commented on serverHomePage/home.html
What is this?

2024-11-21 04:37 UTC, closed without merging